#@package _global_

roi_url: inputs/S1_vSplit_BC_ROI1.geojson

gs_dir: gs://sar4wildfire/Sentinel1
graph_url: graphs/S1_GRD_preprocessing_GEE.xml

platformname: Sentinel-1 # Sentinel-2
producttype: 'GRD' # S2MSI1C S2MSI2A

user: 'ahui0911' # ahui0911
password: '19940911' # 19940911