
project_name: sentinelhub-auto-update

defaults:
- satellite: sentinel1

start_date: "2021-07-30" # None for the day before today
end_date: "2021-07-31" # None for the day after today

# download parameters
download_flag: True
datafolder: D:/Sentinel_Hub # where to save data


# upload parameters
eeUser: omegazhangpzh

exp_name: ${platformname}_${producttype}_${start_date}